### ISSUE TITLE
rv6 shell

### ISSUE THREAD

**Issue by tjhu** [mars-research/redleaf#11]
* [x] Use keyboard driver from PR #10 to get user input.
* [x] Map device drivers to files
* [x] Implement pipe in rv6 fs.(issue #9)
* [x] Implement elf load.(issue #4)

And see more details in the image

![image](https://user-images.githubusercontent.com/18585305/75618553-ec527a80-5b24-11ea-83f2-711a8a3a5e4f.png)
